apiVersion: apps/v1
kind: Deployment
metadata:
  name: strate-go
  labels:
    app: strate-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strate-go
  template:
    metadata:
      labels:
        app: strate-go
    spec:
      containers:
      - name: strate-go
        image: $__IMAGE_NAME:$__IMAGE_TAG
        ports: 
        - containerPort: 12345
        args: ['serve', '--origin', '0.0.0.0', '--port', '12345']
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: strate-go-service
spec:
  type: NodePort
  selector:
    app: strate-go
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      nodePort: 32345
