apiVersion: v1
kind: Deployment
metadata:
  name: strate-go
  labels:
    app: strate-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strate-go
  template:
    metadata:
      labels:
        app: strate-go
    spec:
      containers:
      - name: strate-go
        image: $__IMAGE_NAME:$__IMAGE_TAG
        ports: 
        - containerPort: 12345
        command: ['serve', '--origin', '0.0.0.0', '--port', '12345']
      restartPolicy: OnFailure
